version: "3"
services:
    rethinkdb:
        image: rethinkdb
        ports:
            - "8080:8080"
            - "28015:28015"
            - "29015:29015"
        volumes:
            - ./database:/data
    backend:
        build: ./
        volumes:
            - ./:/usr/src/app
        ports:
            - "8081:8081"
        network_mode: host       
